version: '2.4'

services:
  parsedmarc:
    build:
      context: .
      dockerfile: parsedmarc/Dockerfile
    command: "parsedmarc -c /etc/parsedmarc.ini"
    volumes:
      - ./parsedmarc/parsedmarc.ini:/etc/parsedmarc.ini:z
      #- /path/to/GeoIP:/usr/share/GeoIP
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data/:/usr/share/elasticsearch/data/:z
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - server.name=parsedmarc
      - server.host="0"
      - elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    restart: unless-stopped
    depends_on:
      elasticsearch:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:z
      - ./nginx/ssl/:/etc/nginx/ssl/:z
      - ./nginx/htpasswd:/etc/nginx/htpasswd:z
