version: '3.4'

services:
  parsedmarc:
    build:
      context: ./parsedmarc/
      dockerfile: ./Dockerfile
    environment:
      # in general: <section>.<option>
      parsedmarc.general.save_aggregate: "True"
      parsedmarc.general.save_forensic: "True"
      # parsedmarc.mailbox.watch: "True"
      # parsedmarc.imap.host: "imap.example.com"
      # parsedmarc.imap.user: "parsedmarc@example.com"
      # parsedmarc.imap.password: "somepassword"
      parsedmarc.elasticsearch.hosts: "http://elasticsearch:9200"
      parsedmarc.elasticsearch.ssl: "False"
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/:z
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - server.name=parsedmarc
      - server.host="0"
      - elasticsearch.hosts=http://elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    restart: unless-stopped
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
