services:
  parsedmarc:
    restart: unless-stopped
    build:
      context: ./parsedmarc/
      dockerfile: ./Dockerfile
    networks:
      - app
    env_file:
      - .env
    environment:
      # in general: <section>.<option>
      parsedmarc.general.save_aggregate: "True"
      parsedmarc.general.save_forensic: "True"
      parsedmarc.elasticsearch.hosts: "http://elasticsearch:9200"
      parsedmarc.elasticsearch.ssl: "False"
    depends_on:
      - elasticsearch

  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    networks:
      - app
    environment:
      - cluster.name=parsedmarc
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/:z
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  kibana:
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:8.14.3
    networks:
      - app
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      SERVER_NAME: parsedmarc
      SERVER_HOST: "0.0.0.0"
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
networks:
  app: